### ISSUE TITLE
Make map of z

### ISSUE THREAD

**Issue by AileneKane** [ebuhle/cohoPSM#11]

**Comment by befeist** [comment]
Could you point me toward a .csv with the z scores, or remind me that I already have it?  Thx!

**Comment by AileneKane** [comment]
@befeist Yes! They are are in [PSM_predictions.txt](https://github.com/ebuhle/cohoPSM/blob/master/analysis/results/PSM_predictions.txt). (Z_mean) Thank you!

**Comment by befeist** [comment]
done and in figures dir!

**Comment by AileneKane** [comment]
Thanks @befeist!
